name: 'quench_analytics'
version: '1.0.0'
config-version: 2

profile: 'quench_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  quench_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  project_id: "practical-brace-466015-b1"
  raw_dataset: "raw"
  staging_dataset: "staging"
  analytics_dataset: "analytics" 